# Generated by Django 5.2.6 on 2025-09-15 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=7)),
                ("descricao", models.CharField(max_length=45)),
                ("telemovel", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designacao", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateTimeField()),
                ("data_fim", models.DateTimeField()),
                ("gasto", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Localizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("localidade", models.CharField(max_length=45)),
                ("rua", models.CharField(max_length=45)),
                ("cod_postal", models.CharField(max_length=10)),
                ("capacidade", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Organizador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=45)),
                ("email", models.CharField(max_length=75)),
                ("telemovel", models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.AddField(
            model_name="evento",
            name="localizacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="events.localizacao"
            ),
        ),
    ]
