# Generated by Django 5.2.6 on 2025-09-16 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_artista_categoria_evento_localizacao_organizador_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=45)),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("contact", models.CharField(max_length=20)),
                ("notes", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=45)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("expense", models.DecimalField(decimal_places=2, max_digits=9)),
                ("notes", models.CharField(blank=True, max_length=100, null=True)),
                ("artists", models.ManyToManyField(to="events.artist")),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=45)),
                ("city", models.CharField(max_length=45)),
                ("street", models.CharField(max_length=45)),
                ("zip_code", models.CharField(max_length=10)),
                ("capacity", models.IntegerField()),
                ("notes", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Artista",
        ),
        migrations.RemoveField(
            model_name="evento",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="evento",
            name="localizacao",
        ),
        migrations.DeleteModel(
            name="Organizador",
        ),
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="events.location"
            ),
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
        migrations.DeleteModel(
            name="Evento",
        ),
        migrations.DeleteModel(
            name="Localizacao",
        ),
    ]
